version: '2'

services:
  main:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5005
        --worker-class eventlet
        --access-logfile -
        --reload
        "manage:app"
    volumes:
      - .:/app
    ports:
      - 5005:5005

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  celery:
    build: .
    command: celery worker -l info -P eventlet -A manage.celery
    volumes:
      - .:/app

  flower:
    build: .
    command: celery flower -A manage.celery
    ports:
      - 5555:5555
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    ports:
      - 27017:27017

volumes:
  redis:
  mongo:
